### ISSUE TITLE
Wifi sample script - wifi-controls.js - doesn't actually connect to wifi

### ISSUE THREAD

**Issue by murtazahaveliwala** [tessel/start.tessel.io#85]
I just purchased a tessel and while trying out it's wifi apis. Glancing over wifi samples, i came across this wifi-control.js . 
Issues:

1. While running it on the hardware, i noticed it wasn't connecting to wifi.
    Looking closely, I noticed that there is a 'connect' method but hasn't been invoked.

2. Link to wifi documentation isn't working (404).

**Comment by murtazahaveliwala** [comment]
I have raised a pull request for the same - https://github.com/tessel/start.tessel.io/pull/86

**Comment by johnnyman727** [comment]
@murtazahaveliwala thanks a ton for your contribution! We'll have a community member look it over and merge it as soon as possible.
